# trigger:
# - master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Pay-As-You-Go(2)(15db3464-50a0-4944-a39d-b9a693ef3823)'
    backendAzureRmResourceGroupName: 'NetworkWatcherRG'
    backendAzureRmStorageAccountName: 'omala2'
    backendAzureRmContainerName: 'tfstate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Pay-As-You-Go(3)(15db3464-50a0-4944-a39d-b9a693ef3823)'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Pay-As-You-Go(4)(15db3464-50a0-4944-a39d-b9a693ef3823)'